[project]
name = "cu_weather_app"
version = "1.0.0"
description = "Central University AccuWeather app"
dependencies = [
    "flask",
    "requests"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"